### ISSUE TITLE
Ability to use system libraries/binaries

### ISSUE THREAD

**Issue by jsteel44** [mitchellh/vagrant-installers#111]
It would be great if we could use system libraries/binaries such as ruby and openssl for a start. I don't think I need to explain pros/cons for using system libraries/binaries, but whether you agree or not, could this be added as an option for packagers so they can decide how they want to package/run Vagrant for their users?

I emailed @mitchellh some time ago and he said it was something he'd like to do but didn't have the time right then, but I never did create an "issue" to log the request. Thanks.

**Comment by chrisroberts** [comment]
@jsteel44 Apologies for the delay in reply. The function of this repository is to build an "all-in-one" package. Due to this approach, different versions of the substrate may not work with different versions of Vagrant itself (especially when things like Ruby versions change). The advantage of using system libraries and binaries is indeed known, but there are also advantages of all-in-one packages which include ease of installation for end users, easier issue reproductions, etc. The packages that this repository creates are "official" packages that HashiCorp distributes, and those packages will always be "all-in-one" packages. 

If you are interested in building lightweight packages that pull in all the required dependencies from the system's package manager I'll be happy to help where I can. This repository becomes some what irrelevant for lightweight packages though, since then you won't be doing any vendoring of required binaries/libraries.

Cheers!
